# Generated by Django 2.2.4 on 2019-08-07 19:24

import dictionary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(max_length=40, validators=[dictionary.models.has_numbers]),
        ),
    ]
