# Generated by Django 2.2.4 on 2019-08-07 20:54

import dictionary.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20190807_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(max_length=40, validators=[dictionary.validators.is_alphabetical]),
        ),
    ]
