# Generated by Django 2.2.4 on 2019-08-07 21:38

import dictionary.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20190807_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(max_length=40, unique=True, validators=[dictionary.validators.is_alphabetical]),
        ),
    ]
