# Generated by Django 2.2.4 on 2019-08-08 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0005_auto_20190807_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default='0')),
                ('hits', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Word')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='users',
            field=models.ManyToManyField(through='dictionary.Attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
